### PR TITLE
PUBD-547: port changes from upstream OLH theme for v1.4.1 compatibility

### PR DESCRIPTION
**Pull request by hardyoyo**
* Port changes from upstream OLH theme
* Port change to print.html template made on pub-janeway2-dev
* New features for v1.4.1 reference a number of new settings at the journal and press levels, the following need to be set on dev, stg, prd:
  - journal_settings.general.display_login_page_notice
  - journal_settings.general.login_page_notice
  - press.password.length
  - press.password.upper
  - press.password.number

For the most optimal deployment, those settings should be set correctly, before deploying this update.

### CODE REVIEW

**Comment by justingonder** [comment]
@hardyoyo i have reviewed and updated the settings above on dev, stg & prd. 
In addition to the journal-level settings, I also made sure the defaults for those settings were configured at the press level.

**Comment by hardyoyo** [comment]
the branch for this PR has been deployed on dev for further testing, once that passes, I'll deploy to stg, then we can deploy to prd (not today)

**Comment by hardyoyo** [comment]
also deployed to stg for testing

**Comment by hardyoyo** [comment]
We should probably merge and deploy this to prd sometime this week, I suspect it will improve the functionality of the Glossa site, since a number of the new features for Janeway 1.4.1 required theme changes.

**Review by myucekul — APPROVED** [review]
Looks good to me.

**Pull request merged**
